#pragma once
#include "BasicVideoEffect.g.h"
#include <Generated Files/winrt/Microsoft.Graphics.Canvas.h>
#include <Generated Files/winrt/Microsoft.Graphics.Canvas.Effects.h>

using namespace winrt::Microsoft::Graphics::Canvas::Effects;
using namespace winrt::Microsoft::Graphics::Canvas;

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::FFmpegInteropXWinUI::implementation
{
    struct BasicVideoEffect : BasicVideoEffectT<BasicVideoEffect>
    {
        BasicVideoEffect() = default;

        void SetProperties(winrt::Windows::Foundation::Collections::IPropertySet const& configuration);
        bool IsReadOnly();
        winrt::Windows::Media::Effects::MediaMemoryTypes SupportedMemoryTypes();
        bool TimeIndependent();
        winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Media::MediaProperties::VideoEncodingProperties> SupportedEncodingProperties();
        void SetEncodingProperties(winrt::Windows::Media::MediaProperties::VideoEncodingProperties const& encodingProperties, winrt::Windows::Graphics::DirectX::Direct3D11::IDirect3DDevice const& device);
        void ProcessFrame(winrt::Windows::Media::Effects::ProcessVideoFrameContext const& context);
        void Close(winrt::Windows::Media::Effects::MediaEffectClosedReason const& reason);
        void DiscardQueuedFrames();

    public://internal
        winrt::Windows::Foundation::Collections::IPropertySet inputConfiguration;
        winrt::Microsoft::Graphics::Canvas::CanvasDevice canvasDevice;
        winrt::FFmpegInteropXWinUI::VideoEffectConfiguration EffectConfiguration;


        winrt::Microsoft::Graphics::Canvas::Effects::ICanvasEffect CreateColorEffect(winrt::Microsoft::Graphics::Canvas::ICanvasImage source, float c, float b, float s)
        {
            const auto lumR = 0.2125f;
            const auto lumG = 0.7154f;
            const auto lumB = 0.0721f;

            auto t = (1.0f - c) / 2.0f;
            auto sr = (1.0f - s) * lumR;
            auto sg = (1.0f - s) * lumG;
            auto sb = (1.0f - s) * lumB;

            winrt::Microsoft::Graphics::Canvas::Effects::Matrix5x4 matrix =
            {
                c * (sr + s),	c * (sr),		c * (sr),		0,
                c * (sg),		c * (sg + s),	c * (sg),		0,
                c * (sb),		c * (sb),		c * (sb + s),	0,
                0,				0,				0,				1,
                t + b,			t + b,			t + b,			0
            };

            auto colorMatrixEffect = winrt::Microsoft::Graphics::Canvas::Effects::ColorMatrixEffect();
            colorMatrixEffect.ColorMatrix(matrix);
            colorMatrixEffect.Source(source);

            return colorMatrixEffect;
        }

        winrt::Microsoft::Graphics::Canvas::Effects::ICanvasEffect CreateSharpnessEffect(winrt::Microsoft::Graphics::Canvas::ICanvasImage source, float sharpness, float sharpnessThreshold)
        {
            auto effect = winrt::Microsoft::Graphics::Canvas::Effects::SharpenEffect();
            effect.Amount(sharpness);
            effect.Threshold(sharpnessThreshold);
            effect.Source(source);
            return effect;
        }

        winrt::Microsoft::Graphics::Canvas::Effects::ICanvasEffect CreateTermperatureAndTintEffect(winrt::Microsoft::Graphics::Canvas::ICanvasImage source, float temperature, float tint)
        {
            auto effect = winrt::Microsoft::Graphics::Canvas::Effects::TemperatureAndTintEffect();
            effect.Temperature(temperature);
            effect.Tint(tint);
            effect.Source(source);
            return effect;
        }
    };
}
namespace winrt::FFmpegInteropXWinUI::factory_implementation
{
    struct BasicVideoEffect : BasicVideoEffectT<BasicVideoEffect, implementation::BasicVideoEffect>
    {
    };
}
